#demo_admin:
#    resource: "@DemoAdminBundle/Resources/config/routing.yml"
#    prefix:   /

demo_store:
    resource: "@DemoStoreBundle/Resources/config/routing.yml"
    prefix:   /

demo_web:
    resource: "@DemoWebBundle/Resources/config/routing.yml"
    prefix:   /

hello:
    resource: "@DemoWebBundle/Controller"
    type: annotation
admin:
    resource: "@DemoAdminBundle/Controller"
    type: annotation