parameters:
#    demo_web.example.class: Demo\WebBundle\Example

services:
#    demo_web.example:
#        class: %demo_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
