acme_hello_homepage:
    pattern:  /
    defaults: { _controller: AcmeHelloBundle:Hello:index }

acme_hello:
    pattern:  /hello/ha
    defaults: { _controller: AcmeHelloBundle:Hello:ha }

acme_hello_main:
  pattern: /main
  defaults: { _controller: AcmeHelloBundle:Main:index }