parameters:
#    demo_admin.example.class: Demo\AdminBundle\Example

services:
#    demo_admin.example:
#        class: %demo_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
