parameters:
#    demo_store.example.class: Demo\StoreBundle\Example

services:
#    demo_store.example:
#        class: %demo_store.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
